Project_1/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("random/", views.random_page, name="random"),
    path("wiki", views.search, name="search"),
    path("wiki/<str:name>", views.title, name="title"),
    path("newPage", views.create, name="create"),
    path("edit/<str:name>", views.edit, name="edit")
]

Project_1/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Project_1/encyclopedia/models.py
from django.db import models

# Create your models here.

Project_1/encyclopedia/views.py
import random
import markdown2
from django.shortcuts import render
from django import forms
from . import util
from django.shortcuts import redirect

class searchBar(forms.Form):
    task = forms.CharField(label="Search Encyclopedia")
    
class addForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput)
    description = forms.CharField(widget=forms.Textarea(attrs={'style': "width: 100%"}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "search": searchBar()
    })      

def title(request, name):
    return render(request, "encyclopedia/title.html", {
        "title": name,
        "page": markdown2.markdown(util.get_entry(name)),
        "search": searchBar()
    })

def search(request):
    if request.method == "POST":
        tasks = []
        form = searchBar(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            entries = util.list_entries()
            for entry in entries:
                if task.lower() == entry.lower():
                    return redirect('tasks:title', name=task)
    
                if task.lower() in entry.lower():
                    tasks.append(entry)
            
            if not tasks:
                return redirect('tasks:index')
          
            return render(request, "encyclopedia/index.html", {
                "entries": tasks,
                "search": searchBar()
            })

    if request.method == "GET":
        return redirect('tasks:index')

def create(request):
    if request.method == "POST":
         form = addForm(request.POST)
         if form.is_valid():
            head = form.cleaned_data['title']
            content = form.cleaned_data['description']
            check_existing = util.get_entry(head)
            if check_existing is None:
                util.save_entry(head, content)
                return redirect('tasks:title', name=head)
            
            else:
                return render(request, "encyclopedia/error.html", {
                    "error": "Page already exists",
                    "search": searchBar()
                })
                
                         
    return render(request, "encyclopedia/create.html", {
        "title": "Add a New Page",
        "page": addForm(),
        "search": searchBar()
    })
    
    
def edit(request, name):
    if request.method == "POST":
        form = addForm(request.POST)
        if form.is_valid():
            head = form.cleaned_data['title']
            content = form.cleaned_data['description']
            util.save_entry(head, content)
            return redirect('tasks:title', name=head)
        
    else:  
        initial_data = {
            "title": name,
            "description": util.get_entry(name),
        }
        edit_form = addForm(initial=initial_data)
        return render(request, "encyclopedia/edit.html", {
            "form": edit_form,
            "search": searchBar()
        })

def random_page(request):
    entries = util.list_entries()
    final_entry = random.choice(entries)
    return redirect('tasks:title', name=final_entry)
    
    

Project_1/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <form action="{% url 'tasks:create' %}" method="post">
        {% csrf_token %}
        <div>
            <div>Title</div>
            {{ page.title }}
        </div>

        <div>
            <div>Description</div>
            {{ page.description }}
        </div>

        <button type="submit">Submit</button>
    </form>

{% endblock %}

Project_1/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <form action="{% url 'tasks:edit' form.title%}" method="post">
        {% csrf_token %}
        <div>
            <div>Title</div>
            {{ form.title }}
        </div>

        <div>
            <div>Description</div>
            {{ form.description }}
        </div>

        <button type="submit">Edit</button>
    </form>

{% endblock %}

Project_1/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %} Error {% endblock %}

{% block body %}
    {{ error }}
{% endblock %}

Project_1/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %} Encyclopedia {% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}"> {{ entry }} </a>

            </li>
        {% endfor %}
    </ul>
{% endblock %}

Project_1/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'tasks:search' %}" method="post">
                    {% csrf_token %}
                    {{ search }}
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'tasks:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'tasks:create' %}"> Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'tasks:random' %}"> Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Project_1/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    <h1>Wiki</h1>
{% endblock %}

{% block body %}
{% endblock %}

Project_1/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
        {{ title }}
{% endblock %}

{% block body %}
    <div>
    {{ page | safe }} 
    </div>

    <div>
        <a href="{% url 'tasks:edit' title %}">Edit {{ title }} </a>
    </div>
{% endblock %}